"""added course 2for faculty

Revision ID: 51955b67ba60
Revises: 171008fbfe6e
Create Date: 2026-04-30 16:19:55.089104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51955b67ba60'
down_revision: Union[str, Sequence[str], None] = '171008fbfe6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('course_name2', sa.String(length=70), nullable=True))
    op.alter_column('students', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('faculty', 'course_name2')
    # ### end Alembic commands ###
