"""Add assessment table

Revision ID: e1a1c3165aeb
Revises: fd400e728474
Create Date: 2026-08-15 17:59:15.392315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a1c3165aeb'
down_revision: Union[str, Sequence[str], None] = 'fd400e728474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('course_id', sa.Integer(), nullable=False))
    op.add_column('enrollments', sa.Column('faculty_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'enrollments', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'faculty', ['faculty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'faculty_id')
    op.drop_column('enrollments', 'course_id')
    # ### end Alembic commands ###
