"""Updated sem table

Revision ID: f974c6e09c53
Revises: 8c45af4a1d92
Create Date: 2026-05-06 18:03:24.610868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f974c6e09c53'
down_revision: Union[str, Sequence[str], None] = '8c45af4a1d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semesters', sa.Column('code', sa.String(length=10), nullable=False))
    op.add_column('semesters', sa.Column('semester_number', sa.Integer(), nullable=False))
    op.alter_column('semesters', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('semesters', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('semesters', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('semesters', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('semesters', 'semester_number')
    op.drop_column('semesters', 'code')
    # ### end Alembic commands ###
