"""refactor faculty course relation

Revision ID: f98c00dae9f3
Revises: 51955b67ba60
Create Date: 2026-05-06 15:44:38.584926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98c00dae9f3'
down_revision: Union[str, Sequence[str], None] = '51955b67ba60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty', 'course_name2')
    op.drop_column('faculty', 'course_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('course_name', sa.VARCHAR(length=70), autoincrement=False, nullable=False))
    op.add_column('faculty', sa.Column('course_name2', sa.VARCHAR(length=70), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
