"""i'm tired

Revision ID: fd400e728474
Revises: fb4212a63768
Create Date: 2026-05-06 18:10:32.668131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd400e728474'
down_revision: Union[str, Sequence[str], None] = 'fb4212a63768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semesters', sa.Column('semester_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semesters', 'semester_type')
    # ### end Alembic commands ###
